// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package widgets

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LeftMenu() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = LeftMenuStyle().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		login := ctx.Value("login").(string)
		MyProfileHref := "/profile/" + login
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"left-menu\"><div class=\"link-wrapper\"><img width=\"18px\" height=\"18px\" src=\"/public/icons/user2.svg\" alt=\"user ico\" class=\"icon\"> <a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.SafeURL = templ.SafeURL(MyProfileHref)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var2)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"link\">Мой профиль</a></div><div class=\"link-wrapper\"><img width=\"18px\" height=\"18px\" src=\"/public/icons/feed.svg\" alt=\"feed ico\" class=\"icon\"> <a href=\"/feed\" class=\"link\">Новости</a></div><div class=\"link-wrapper\"><img width=\"18px\" height=\"18px\" src=\"/public/icons/chats.svg\" alt=\"chats ico\" class=\"icon\"> <a href=\"/messages\">Сообщения</a></div><div class=\"link-wrapper\"><img width=\"18px\" height=\"18px\" src=\"/public/icons/friends.svg\" alt=\"friends ico\" class=\"icon\"> <a href=\"/friends\">Друзья</a></div><div class=\"link-wrapper\"><img width=\"18px\" height=\"18px\" src=\"/public/icons/people.svg\" alt=\"people ico\" class=\"icon\"> <a href=\"/people\">Люди</a></div><div class=\"link-wrapper\"><img width=\"18px\" height=\"18px\" src=\"/public/icons/group.svg\" alt=\"groups ico\" class=\"icon\"> <a href=\"/groups\">Группы</a></div><div class=\"link-wrapper\"><img width=\"18px\" height=\"18px\" src=\"/public/icons/photos.svg\" alt=\"photos ico\" class=\"icon\"> <a href=\"/photos\">Фотографии</a></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// position: sticky;
func LeftMenuStyle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<style>\r\n\r\n    .link{\r\n        padding-left: 0px;\r\n    }\r\n\r\n    .icon{\r\n        margin-left: 15px;\r\n    }\r\n\r\n    .link-wrapper:hover{\r\n        background-color: #303030;\r\n        \r\n    }\r\n    \r\n    .link-wrapper{\r\n        display: flex;\r\n        flex-direction: row;\r\n        justify-content: left;\r\n        align-items: center;\r\n        border-radius: 20px;\r\n        transition: all 0.3s ease-in-out\r\n    }\r\n\r\n    .left-menu {\r\n        min-width: 220px;\r\n        max-width: 220px;\r\n        background-color: #0c0c0c;\r\n        color: white;\r\n        height: 100vh;\r\n        \r\n        top: 0;\r\n    }\r\n    \r\n    .left-menu a {\r\n        display: block;\r\n        color: white;\r\n        text-decoration: none;\r\n        padding: 15px 10px;\r\n        transition: background-color 0.3s;\r\n    }\r\n    \r\n    .left-menu a:hover {\r\n        \r\n    }\r\n    \r\n    .left-menu .menu-title {\r\n        font-weight: bold;\r\n        padding: 15px 20px 5px;\r\n        color: #bdc3c7;\r\n        font-size: 14px;\r\n        text-transform: uppercase;\r\n    }\r\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
