// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package widgets

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ModuleCard(login string, defaultModule string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ModuleCardStyle().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"modulecard-wrapper\"><div class=\"modulecard-header--wrapper\"><div class=\"photomodule-text module-tab active-tab\" onclick=\"switchModule(&#39;photo&#39;)\">Фото</div><div class=\"friendmodule-text module-tab\" onclick=\"switchModule(&#39;friend&#39;)\">Друзья</div><div class=\"groupmodule-text module-tab\" onclick=\"switchModule(&#39;group&#39;)\">Группы</div></div><div class=\"chosen-module-wrapper\"><div id=\"module-content\" class=\"module-content\"></div></div></div><script>\r\n\r\n        const userLogin = ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2, templ_7745c5c3_Err := templruntime.ScriptContentOutsideStringLiteral(login)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/widgets/userpageModules.templ`, Line: 26, Col: 34}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, ";\r\n        const DefaultModuleJS = ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3, templ_7745c5c3_Err := templruntime.ScriptContentOutsideStringLiteral(defaultModule)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/widgets/userpageModules.templ`, Line: 27, Col: 48}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, ";\r\n        \r\n        document.addEventListener('DOMContentLoaded', function() {\r\n\r\n            updateActiveTab(DefaultModuleJS);\r\n            loadModuleContent(DefaultModuleJS, userLogin);\r\n        });\r\n\r\n        function switchModule(moduleName) {\r\n            updateActiveTab(moduleName);\r\n            loadModuleContent(moduleName, userLogin);\r\n        }\r\n\r\n        function updateActiveTab(moduleName) {\r\n            document.querySelectorAll('.module-tab').forEach(tab => {\r\n                tab.classList.remove('active-tab');\r\n            });\r\n            document.querySelector(`.${moduleName}module-text`).classList.add('active-tab');\r\n        }\r\n\r\n        function loadModuleContent(moduleName, login) {\r\n            fetch(`/api/module-content?module=${encodeURIComponent(moduleName)}&login=${encodeURIComponent(login)}`)\r\n                .then(response => {\r\n                    if (!response.ok) throw new Error('Network response was not ok');\r\n                    return response.text();\r\n                })\r\n                .then(html => {\r\n                    document.getElementById('module-content').innerHTML = html;\r\n                })\r\n                .catch(error => {\r\n                    console.error('Error loading module content:', error);\r\n                    document.getElementById('module-content').innerHTML = `\r\n                        <div class=\"error-message\">\r\n                            Ошибка загрузки контента. Пожалуйста, попробуйте позже.\r\n                        </div>\r\n                    `;\r\n                });\r\n        }\r\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ModuleCardStyle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<style>\r\n        .modulecard-header--wrapper {\r\n            gap: 5px;\r\n            display: flex;\r\n            justify-content: left;\r\n            padding: 0 15px;\r\n            margin: 0 auto;\r\n            align-items: center;\r\n            box-sizing: border-box;\r\n            max-width: 1100px;\r\n            width: 100%;\r\n            height: 60px;\r\n            border-radius: 20px 20px 0 0;\r\n            border-bottom: 3px solid #0c0c0c;\r\n        }\r\n        .modulecard-wrapper {\r\n            display: flex;\r\n            flex-direction: column;\r\n            border-radius: 20px;\r\n            width: 100%;\r\n            max-width: 1100px;\r\n            margin: 0 auto;\r\n            background: #222222;\r\n            margin-bottom: 15px;\r\n            \r\n        }\r\n        .module-tab {\r\n            cursor: pointer;\r\n            gap: 10px;\r\n            padding: 8px 16px;\r\n            border-radius: 8px;\r\n            transition: all 0.3s ease;\r\n            color: #888;\r\n        }\r\n        .module-tab:hover {\r\n            background-color: #333;\r\n            color: #ccc;\r\n        }\r\n        .active-tab {\r\n            background-color: #444;\r\n            color: white;\r\n            box-shadow: 0 2px 5px rgba(0,0,0,0.2);\r\n        }\r\n        .module-content {\r\n            padding-left: 15px;\r\n            max-height: 215px;\r\n            display: flex;\r\n            align-items: center;\r\n        }\r\n        .error-message {\r\n            color: #ff4444;\r\n            padding: 20px;\r\n            text-align: center;\r\n        }\r\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
