// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type PeopleProfileCardCredentials struct {
	Login      string
	AvatarPath string
	Role       int
}

func PeopleCard(userCredentials PeopleProfileCardCredentials) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = PeopleCardStyle().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"people-card--wrapper\"><div class=\"card\"><div class=\"wrapper\"><div class=\"avatar\"><img class=\"profile-avatar\" crossorigin=\"anonymous\" src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(userCredentials.AvatarPath)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/people-card.templ`, Line: 16, Col: 104}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" alt=\"Изображение профиля\"></div><div class=\"user-info-wrapper\"><div class=\"login\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(userCredentials.Login)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/people-card.templ`, Line: 20, Col: 47}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"role\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var userRole string
		if userCredentials.Role == 0 {
			userRole = "Пользователь"
		}
		if userCredentials.Role == 1 {
			userRole = "Администратор"
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(userRole)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/people-card.templ`, Line: 26, Col: 34}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div></div></div><div class=\"addfriend\">1</div><div class=\"sendmessage\">2</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func PeopleCardStyle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<style>\r\n        .wrapper{\r\n            margin-left: 15px;\r\n            flex-direction: row;\r\n            display: flex;\r\n            justify-content: left;\r\n            align-items: center;\r\n        }\r\n\r\n        .profile-avatar {\r\n\r\n            width: 60px;\r\n            height: 60px;\r\n            border-radius: 50%;\r\n            object-fit: cover;\r\n            \r\n        }\r\n\r\n        .avatar{\r\n            width: 60px;\r\n            height: 60px;\r\n        }\r\n\r\n        .people-card--wrapper{\r\n            display: flex;\r\n            flex-direction: row;\r\n            max-width: 1100px;\r\n            width: 100%;\r\n            \r\n            min-height: 90px;\r\n            height: 100%;\r\n        }\r\n\r\n        .user-info-wrapper{\r\n            margin-left: 15px;\r\n            display: flex;\r\n            flex-direction: column;\r\n            color: white;\r\n        }\r\n        \r\n        .sendmessage\r\n        {\r\n            border-radius: 20px;\r\n            max-width: 90px;\r\n            margin-left: 15px;\r\n            width: 100%;\r\n            min-height: 90px;\r\n            height: 100%;\r\n            background-color: #222222;\r\n        }\r\n        .addfriend{\r\n            border-radius: 20px;\r\n            max-width: 90px;\r\n            margin-left: 15px;\r\n            width: 100%;\r\n            min-height: 90px;\r\n            height: 100%;\r\n            background-color: #222222;\r\n        }\r\n\r\n        .card{\r\n            display: flex;\r\n            flex-direction: row;\r\n            border-radius: 20px;\r\n            max-width: 890px;\r\n            width: 100%;\r\n            min-height: 90px;\r\n            height: 100%;\r\n            background-color: #222222;\r\n            align-items: center;\r\n\r\n        }\r\n    \r\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
